import { UIDocumentSchema } from '@haku/ui'

const id = (value: number): string =>
  `b1200000-0000-4000-8000-${value.toString().padStart(12, '0')}`

export const BOUNCE_RUN_UI_IDS = {
  document: id(1),
  root: id(2),
  startPanel: id(3),
  startTitle: id(4),
  startHelp: id(5),
  startButton: id(6),
  hudPanel: id(7),
  stateText: id(8),
  performanceText: id(9),
  pausePanel: id(10),
  pauseTitle: id(11),
  resumeButton: id(12),
  gameOverPanel: id(13),
  gameOverTitle: id(14),
  restartButton: id(15),
  events: {
    start: id(30),
    resume: id(31),
    restart: id(32),
  },
} as const

export const bounceRunUIDocument = UIDocumentSchema.parse({
  schemaVersion: 1,
  id: BOUNCE_RUN_UI_IDS.document,
  name: 'Bounce Run HUD',
  root: BOUNCE_RUN_UI_IDS.root,
  elements: [
    {
      id: BOUNCE_RUN_UI_IDS.root,
      type: 'container',
      children: [
        BOUNCE_RUN_UI_IDS.startPanel,
        BOUNCE_RUN_UI_IDS.hudPanel,
        BOUNCE_RUN_UI_IDS.pausePanel,
        BOUNCE_RUN_UI_IDS.gameOverPanel,
      ],
      sizing: { width: '100%', height: '100%' },
      accessibility: { role: 'application', label: 'Bounce Run' },
    },
    {
      id: BOUNCE_RUN_UI_IDS.startPanel,
      type: 'container',
      children: [
        BOUNCE_RUN_UI_IDS.startTitle,
        BOUNCE_RUN_UI_IDS.startHelp,
        BOUNCE_RUN_UI_IDS.startButton,
      ],
      layout: { direction: 'column', align: 'center', gap: 14 },
      anchors: { left: 0, right: 0, top: 0, bottom: 0 },
      style: {
        color: '#f9fff1',
        backgroundColor: '#13233b',
        fontFamily: 'system-ui, sans-serif',
        padding: 32,
      },
    },
    {
      id: BOUNCE_RUN_UI_IDS.startTitle,
      type: 'text',
      text: 'BOUNCE RUN',
      style: { color: '#f9e86c', fontSize: 42, fontWeight: 'bold' },
    },
    {
      id: BOUNCE_RUN_UI_IDS.startHelp,
      type: 'text',
      text: 'A / D or arrow keys to steer · Escape to pause · R to restart',
      style: { color: '#d9f0ff', fontSize: 16, textAlign: 'center' },
    },
    {
      id: BOUNCE_RUN_UI_IDS.startButton,
      type: 'button',
      text: 'Start run',
      activateEvent: BOUNCE_RUN_UI_IDS.events.start,
      accessibility: { label: 'Start Bounce Run' },
      style: {
        color: '#102038',
        backgroundColor: '#f9e86c',
        fontSize: 20,
        fontWeight: 'bold',
        padding: 14,
        borderColor: '#ffffff',
        borderWidth: 2,
        borderRadius: 12,
        cursor: 'pointer',
      },
    },
    {
      id: BOUNCE_RUN_UI_IDS.hudPanel,
      type: 'container',
      children: [BOUNCE_RUN_UI_IDS.stateText, BOUNCE_RUN_UI_IDS.performanceText],
      layout: { direction: 'column', gap: 4 },
      anchors: { left: 18, top: 18 },
      style: {
        color: '#ffffff',
        backgroundColor: '#13233b',
        fontFamily: 'system-ui, sans-serif',
        padding: 12,
        borderColor: '#77d9ff',
        borderWidth: 2,
        borderRadius: 10,
      },
    },
    {
      id: BOUNCE_RUN_UI_IDS.stateText,
      type: 'text',
      text: 'start',
      accessibility: { live: 'polite' },
      style: { color: '#f9e86c', fontSize: 16, fontWeight: 'bold' },
    },
    {
      id: BOUNCE_RUN_UI_IDS.performanceText,
      type: 'text',
      text: 'Measuring baseline…',
      style: { color: '#d9f0ff', fontSize: 12 },
    },
    {
      id: BOUNCE_RUN_UI_IDS.pausePanel,
      type: 'container',
      children: [BOUNCE_RUN_UI_IDS.pauseTitle, BOUNCE_RUN_UI_IDS.resumeButton],
      layout: { direction: 'column', align: 'center', gap: 14 },
      anchors: { left: 0, right: 0, top: 0, bottom: 0 },
      style: {
        color: '#ffffff',
        backgroundColor: '#26344f',
        fontFamily: 'system-ui, sans-serif',
        padding: 32,
      },
    },
    {
      id: BOUNCE_RUN_UI_IDS.pauseTitle,
      type: 'text',
      text: 'Paused',
      style: { color: '#77d9ff', fontSize: 36, fontWeight: 'bold' },
    },
    {
      id: BOUNCE_RUN_UI_IDS.resumeButton,
      type: 'button',
      text: 'Resume',
      activateEvent: BOUNCE_RUN_UI_IDS.events.resume,
      style: {
        color: '#102038',
        backgroundColor: '#77d9ff',
        fontSize: 18,
        padding: 12,
        borderRadius: 10,
        cursor: 'pointer',
      },
    },
    {
      id: BOUNCE_RUN_UI_IDS.gameOverPanel,
      type: 'container',
      children: [BOUNCE_RUN_UI_IDS.gameOverTitle, BOUNCE_RUN_UI_IDS.restartButton],
      layout: { direction: 'column', align: 'center', gap: 14 },
      anchors: { left: 0, right: 0, top: 0, bottom: 0 },
      style: {
        color: '#ffffff',
        backgroundColor: '#3b1835',
        fontFamily: 'system-ui, sans-serif',
        padding: 32,
      },
    },
    {
      id: BOUNCE_RUN_UI_IDS.gameOverTitle,
      type: 'text',
      text: 'Run over',
      style: { color: '#ff7a99', fontSize: 36, fontWeight: 'bold' },
    },
    {
      id: BOUNCE_RUN_UI_IDS.restartButton,
      type: 'button',
      text: 'Run again',
      activateEvent: BOUNCE_RUN_UI_IDS.events.restart,
      style: {
        color: '#321122',
        backgroundColor: '#ffb5c7',
        fontSize: 18,
        padding: 12,
        borderRadius: 10,
        cursor: 'pointer',
      },
    },
  ],
  events: [
    { id: BOUNCE_RUN_UI_IDS.events.start, name: 'start-session', payload: 'none' },
    { id: BOUNCE_RUN_UI_IDS.events.resume, name: 'resume-session', payload: 'none' },
    { id: BOUNCE_RUN_UI_IDS.events.restart, name: 'restart-session', payload: 'none' },
  ],
})
